In [8]:
import numpy as np
import pandas as pd

In [9]:
student_df=pd.DataFrame({
    "Name": ["prabhav", "pranav", "chirag", "divyansh"],
    "Age": [19, 20, 18, 21],
    "City": ["gorakhpur", "patna", "delhi", "lucknow"]
})

In [10]:
student_df

       Name  Age       City
0   prabhav   19  gorakhpur
1    pranav   20      patna
2    chirag   18      delhi
3  divyansh   21    lucknow

In [11]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [12]:
student_df["Name"]

0     prabhav
1      pranav
2      chirag
3    divyansh
Name: Name, dtype: object

In [13]:
student_df["City"]

0    gorakhpur
1        patna
2        delhi
3      lucknow
Name: City, dtype: object

In [14]:
name_city_df=student_df[["Name", "City"]]
name_city_df

       Name       City
0   prabhav  gorakhpur
1    pranav      patna
2    chirag      delhi
3  divyansh    lucknow

In [15]:
book_df=pd.DataFrame({
    "Book": ["NLP with Pyton", "Machine Learning", "LLM"],
    "Author": ["Steven Bird", "Aurélien Géron", "Maarten Grootendorst"],
    "Price": [450, 600, 750]
})

In [16]:
book_df["Publisher"]="O’Reilly"
book_df

               Book                Author  Price Publisher
0    NLP with Pyton           Steven Bird    450  O’Reilly
1  Machine Learning        Aurélien Géron    600  O’Reilly
2               LLM  Maarten Grootendorst    750  O’Reilly

In [17]:
ser_df=pd.DataFrame({
    "Item": ["pen", "pencil", "dairy", "copy", "book"]
})

In [18]:
ser_df["SerialNo"]=np.arange(5)
ser_df

     Item  SerialNo
0     pen         0
1  pencil         1
2   dairy         2
3    copy         3
4    book         4

In [19]:
ser_df.drop(columns=["SerialNo"], inplace=True)
ser_df

     Item
0     pen
1  pencil
2   dairy
3    copy
4    book

In [20]:
movie_df=pd.DataFrame({
    "Movie": ["Inception", "Interstellar", "Jumanji"],
    "Year": [2010, 2014, 2017],
    "Rating": [8.8, 8.7, 7.9]
})
movie_df

          Movie  Year  Rating
0     Inception  2010     8.8
1  Interstellar  2014     8.7
2       Jumanji  2017     7.9

In [21]:
movie_new_df=movie_df.reindex(columns=["Movie", "Rating", "Director"])
movie_new_df

          Movie  Rating  Director
0     Inception     8.8       NaN
1  Interstellar     8.7       NaN
2       Jumanji     7.9       NaN

In [22]:
city_df=pd.Series(["Lucknow", "Mathura"],index=[0, 3])
city_df

0    Lucknow
3    Mathura
dtype: object

In [23]:
branch_df=pd.DataFrame({"Student": ["prabhav", "pranav", "chirag", "divyansh"]})
branch_df["branch"]=city_df
branch_df

    Student   branch
0   prabhav  Lucknow
1    pranav      NaN
2    chirag      NaN
3  divyansh  Mathura

In [24]:
employee_df=pd.DataFrame({
    "Employee": ["prabhav", "abhishek", "pranav", "chirag", "divyansh"],
    "Department": ["IT", "HR", "Finance", "Marketing", "IT"],
    "Experience": [2, 4, 1, 3, 5]
})

In [25]:
experience_df=employee_df[["Employee", "Experience"]]
experience_df

   Employee  Experience
0   prabhav           2
1  abhishek           4
2    pranav           1
3    chirag           3
4  divyansh           5

In [26]:
employee_df["Department"]
employee_df.columns

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [27]:
employee_df["Office"]="Head Office"
employee_df

   Employee Department  Experience       Office
0   prabhav         IT           2  Head Office
1  abhishek         HR           4  Head Office
2    pranav    Finance           1  Head Office
3    chirag  Marketing           3  Head Office
4  divyansh         IT           5  Head Office

In [28]:
employee_df["Office"]=np.arange(5)
employee_df

   Employee Department  Experience  Office
0   prabhav         IT           2       0
1  abhishek         HR           4       1
2    pranav    Finance           1       2
3    chirag  Marketing           3       3
4  divyansh         IT           5       4

In [29]:
office=pd.Series(["lucknow", "mathura", "delhi"], index=[0, 2, 4])
employee_df=office
employee_df

0    lucknow
2    mathura
4      delhi
dtype: object

In [30]:
employee_df.drop(columns=["office"], inplace=True)
employee_df

0    lucknow
2    mathura
4      delhi
dtype: object

In [31]:
product_df=pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard"],
    "Category": ["Electronics", "Accessories", "Accessories"],
    "Price": [155000, 1000, 2000]
})
ordered_df=product_df[["Price","Product","Category"]]
ordered_df

    Price   Product     Category
0  155000    Laptop  Electronics
1    1000     Mouse  Accessories
2    2000  Keyboard  Accessories

In [32]:
result = product_df.reindex(columns=["Product", "Category", "Price", "Brand"])
result

    Product     Category   Price  Brand
0    Laptop  Electronics  155000    NaN
1     Mouse  Accessories    1000    NaN
2  Keyboard  Accessories    2000    NaN

In [33]:
marks_df = pd.DataFrame({
    "Student": ["Aman", "Riya", "Karan"],
    "Total Marks": [85, 92, 78]
})
marks_df["Total Marks"]

0    85
1    92
2    78
Name: Total Marks, dtype: int64

In [39]:
course_df = pd.DataFrame({
    "Student": ["Aman", "Riya", "Karan", "Neha", "Vikram"],
    "Course": ["Python", "Java", "Python", "SQL", "C++"],
    "Score": [85, 92, 78, 88, 95]
})
course_df.columns

Index(['Student', 'Course', 'Score'], dtype='object')

In [40]:
course_df["Student"]

0      Aman
1      Riya
2     Karan
3      Neha
4    Vikram
Name: Student, dtype: object

In [41]:
student_score = course_df[["Student", "Score"]]
student_score

  Student  Score
0    Aman     85
1    Riya     92
2   Karan     78
3    Neha     88
4  Vikram     95

In [42]:
course_df["Batch"] = "2026"
course_df

  Student  Course  Score Batch
0    Aman  Python     85  2026
1    Riya    Java     92  2026
2   Karan  Python     78  2026
3    Neha     SQL     88  2026
4  Vikram     C++     95  2026

In [43]:
travel_df = pd.DataFrame({
    "place": ["Delhi", "Mathura", "Agra", "Jaipur", "Lucknow"],
    "distance": [200, 1400, 230, 280, 1800],
    "vehicle": ["Car", "Train", "Bus", "Car", "Flight"],
    "price": [3000, 5000, 2000, 3500, 8000],
    "days": [2, 5, 2, 3, 6]
})
travel_df["Code"] = np.arange(5)
travel_df

     place  distance vehicle  price  days  Code
0    Delhi       200     Car   3000     2     0
1  Mathura      1400   Train   5000     5     1
2     Agra       230     Bus   2000     2     2
3   Jaipur       280     Car   3500     3     3
4  Lucknow      1800  Flight   8000     6     4

In [47]:
code = pd.Series(
    ["x", "y"],
    index=[1, 4],
    name="Code"
)
travel_df["Code"] = code
travel_df

     place  distance vehicle  price  days Code
0    Delhi       200     Car   3000     2  NaN
1  Mathura      1400   Train   5000     5    x
2     Agra       230     Bus   2000     2  NaN
3   Jaipur       280     Car   3500     3  NaN
4  Lucknow      1800  Flight   8000     6    y

In [52]:
school_df = pd.DataFrame({
    "Student": ["Aman", "Riya", "Karan"],
    "Class": [4, 5, 6],
    "Section": ["A", "B", "c"]
})
new = school_df.reindex( columns=["Student", "Class", "Section", "House"])
new

  Student  Class Section  House
0    Aman      4       A    NaN
1    Riya      5       B    NaN
2   Karan      6       c    NaN

In [54]:
new["House"] = "Red"
new

  Student  Class Section House
0    Aman      4       A   Red
1    Riya      5       B   Red
2   Karan      6       c   Red

In [60]:
inventory_df=pd.DataFrame({
    "Product": ["laptop", "mouse", "keyboard"],
    "Category": ["electronics", "accessories", "accessories"],
    "Price": [155000, 1000, 2000]
})

stock_series = pd.Series(
    [5, 12],
    index=[0, 2],
    name= "restock"
)

inventory_df["restock"] = stock_series
inventory_df

    Product     Category   Price  restock
0    laptop  electronics  155000      5.0
1     mouse  accessories    1000      NaN
2  keyboard  accessories    2000     12.0

In [62]:
del inventory_df["restock"]
inventory_df

    Product     Category   Price
0    laptop  electronics  155000
1     mouse  accessories    1000
2  keyboard  accessories    2000